In [1]:
import numpy as np

In [11]:
#直接将列表转化为array类型
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
type(arr1)


numpy.ndarray

In [12]:
arr1.shape

(2, 5)

In [14]:
arr2=np.zeros(shape=(2,2))
print(arr2)

[[ 0.  0.]
 [ 0.  0.]]


In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr1.dtype

dtype('int32')

In [20]:
np.array([[1.1,1.2],[2.1,2.3]],dtype='int32')

array([[1, 1],
       [2, 2]])

In [27]:
arr3=np.array(['1','2','3','4'])
arr3=arr3.astype(np.string_)
arr3.astype(np.int64)

array([1, 2, 3, 4], dtype=int64)

In [28]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [29]:
1+arr1

array([[2, 3, 4],
       [5, 6, 7]])

In [32]:
arr1=np.array([[1,3,5],[7,9,11]])
arr2=np.array([[2,4,6],[6,8,10]])
arr3=arr1>arr2
arr3

array([[False, False, False],
       [ True,  True,  True]], dtype=bool)

In [33]:
list1=[1,2,3,4]
list2=list1[1:]
list2[0]=3
list1

[1, 2, 3, 4]

In [44]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=arr1[:,1:].copy()
arr2[0]=[5,6]
arr1[:,0:]
arr1[0,1:]

array([2, 3])

In [60]:
#布尔索引
names=np.array(['kirito','asuna','xilika','yuyi'])
data=np.random.randn(4,3)
print(data)
print(data[(names=='kirito')|(names=='asuna'),1:])
print(data[~(names=='kirito')])


[[-0.91293326 -1.27942019 -1.09682988]
 [-1.46805471  1.34450759 -1.11832568]
 [ 0.74090402  0.64368017 -1.26457304]
 [-1.0548294   1.01918918 -0.81496727]]
[[-1.27942019 -1.09682988]
 [ 1.34450759 -1.11832568]]
[[-1.46805471  1.34450759 -1.11832568]
 [ 0.74090402  0.64368017 -1.26457304]
 [-1.0548294   1.01918918 -0.81496727]]


In [64]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
print(arr)
print(arr[[3,0,4]])
print(arr[[3,0,4]][:,[0,2,1]])

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]]
[[ 3.  3.  3.  3.]
 [ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]]
[[ 3.  3.  3.]
 [ 0.  0.  0.]
 [ 4.  4.  4.]]


In [72]:
arr=np.array([[1,2,3],[4,5,6]])


array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
arr=np.arange(10)
np.sqrt(arr)


array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [87]:
arr=np.arange(10)
arr2=np.arange(start=10,stop=20)
np.maximum(arr,arr2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [1]:
arr=np.random.randn(4,4)
arr2=np.array([1,2,3])
np.where(arr>0,arr,1)

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
arr=np.random.randn(100)

In [6]:
arr

array([ 1.84984668e+00, -6.03953432e-03,  4.34632747e-01, -5.66104407e-01,
       -8.97271636e-01, -1.40449809e+00,  1.57121658e+00, -3.24409104e-01,
        1.22390171e+00, -3.38530361e-01,  1.32738988e+00,  7.43073836e-01,
        3.48761572e-01,  3.73084930e-01,  1.34328091e+00, -8.75622032e-01,
       -1.56150522e+00, -2.04820054e+00, -7.30320878e-01, -4.93318032e-01,
       -3.60064722e-01, -2.75800095e+00,  1.25821374e-01,  3.49130987e-01,
       -1.93073465e+00,  9.58736213e-01, -1.18504446e+00, -5.31163160e-02,
        9.89221459e-01, -1.62299803e-01,  2.00111733e-01, -4.55662943e-01,
       -5.25200504e-01, -2.32250504e-01,  6.95139793e-01,  1.71517885e+00,
        2.28166154e-02, -1.76319529e+00, -1.36781509e+00,  3.38997332e-01,
       -9.02658179e-01,  1.53213475e-01, -4.46363684e-02, -3.59491960e-01,
       -6.98786633e-01,  4.39745319e-01, -1.02516940e+00,  9.90179000e-01,
       -6.36872442e-01, -3.26619568e-01, -9.64866229e-01,  5.14796015e-03,
        1.52482753e+00,  

In [7]:
arr.sum()

-6.26307534698422

In [9]:
(arr>0).sum()

48

In [10]:
arr.any()

True

In [11]:
arr

array([ 1.84984668e+00, -6.03953432e-03,  4.34632747e-01, -5.66104407e-01,
       -8.97271636e-01, -1.40449809e+00,  1.57121658e+00, -3.24409104e-01,
        1.22390171e+00, -3.38530361e-01,  1.32738988e+00,  7.43073836e-01,
        3.48761572e-01,  3.73084930e-01,  1.34328091e+00, -8.75622032e-01,
       -1.56150522e+00, -2.04820054e+00, -7.30320878e-01, -4.93318032e-01,
       -3.60064722e-01, -2.75800095e+00,  1.25821374e-01,  3.49130987e-01,
       -1.93073465e+00,  9.58736213e-01, -1.18504446e+00, -5.31163160e-02,
        9.89221459e-01, -1.62299803e-01,  2.00111733e-01, -4.55662943e-01,
       -5.25200504e-01, -2.32250504e-01,  6.95139793e-01,  1.71517885e+00,
        2.28166154e-02, -1.76319529e+00, -1.36781509e+00,  3.38997332e-01,
       -9.02658179e-01,  1.53213475e-01, -4.46363684e-02, -3.59491960e-01,
       -6.98786633e-01,  4.39745319e-01, -1.02516940e+00,  9.90179000e-01,
       -6.36872442e-01, -3.26619568e-01, -9.64866229e-01,  5.14796015e-03,
        1.52482753e+00,  

In [14]:
arr2=np.where(arr>0,True,False)

In [15]:
arr2

array([ True, False,  True, False, False, False,  True, False,  True,
       False,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False,  True,  True, False,  True, False,
       False,  True, False,  True, False, False, False,  True,  True,
        True, False, False,  True, False,  True, False, False, False,
        True, False,  True, False, False, False,  True,  True,  True,
       False, False, False,  True, False, False,  True,  True,  True,
        True, False,  True, False,  True, False, False, False,  True,
        True,  True, False, False,  True,  True,  True,  True, False,
       False,  True,  True, False,  True,  True, False, False, False,
        True, False,  True,  True,  True, False,  True, False,  True,
       False])

In [16]:
arr2.sum()

48

In [17]:
arr.sort()

In [18]:
arr

array([-2.75800095e+00, -2.62415011e+00, -2.27379667e+00, -2.04820054e+00,
       -1.93073465e+00, -1.76319529e+00, -1.56150522e+00, -1.40449809e+00,
       -1.36781509e+00, -1.32990443e+00, -1.18504446e+00, -1.09510542e+00,
       -1.02516940e+00, -1.01736746e+00, -9.64866229e-01, -9.02658179e-01,
       -8.97271636e-01, -8.75622032e-01, -8.62867233e-01, -8.21153934e-01,
       -8.14071756e-01, -7.30320878e-01, -6.98786633e-01, -6.74430882e-01,
       -6.36872442e-01, -6.18998738e-01, -5.66104407e-01, -5.25200504e-01,
       -5.03654973e-01, -4.93318032e-01, -4.55662943e-01, -4.29903394e-01,
       -4.28548616e-01, -3.63177945e-01, -3.60064722e-01, -3.59491960e-01,
       -3.38530361e-01, -3.26619568e-01, -3.24409104e-01, -2.32250504e-01,
       -1.73852626e-01, -1.62299803e-01, -1.51520762e-01, -1.16078268e-01,
       -9.84103499e-02, -9.61372773e-02, -6.96719660e-02, -5.31163160e-02,
       -4.46363684e-02, -1.85853638e-02, -6.03953432e-03, -1.33194141e-03,
        5.14796015e-03,  

In [19]:
np.unique(arr)

array([-2.75800095e+00, -2.62415011e+00, -2.27379667e+00, -2.04820054e+00,
       -1.93073465e+00, -1.76319529e+00, -1.56150522e+00, -1.40449809e+00,
       -1.36781509e+00, -1.32990443e+00, -1.18504446e+00, -1.09510542e+00,
       -1.02516940e+00, -1.01736746e+00, -9.64866229e-01, -9.02658179e-01,
       -8.97271636e-01, -8.75622032e-01, -8.62867233e-01, -8.21153934e-01,
       -8.14071756e-01, -7.30320878e-01, -6.98786633e-01, -6.74430882e-01,
       -6.36872442e-01, -6.18998738e-01, -5.66104407e-01, -5.25200504e-01,
       -5.03654973e-01, -4.93318032e-01, -4.55662943e-01, -4.29903394e-01,
       -4.28548616e-01, -3.63177945e-01, -3.60064722e-01, -3.59491960e-01,
       -3.38530361e-01, -3.26619568e-01, -3.24409104e-01, -2.32250504e-01,
       -1.73852626e-01, -1.62299803e-01, -1.51520762e-01, -1.16078268e-01,
       -9.84103499e-02, -9.61372773e-02, -6.96719660e-02, -5.31163160e-02,
       -4.46363684e-02, -1.85853638e-02, -6.03953432e-03, -1.33194141e-03,
        5.14796015e-03,  

In [20]:
arr=np.random.randn(5,3)

In [21]:
arr

array([[ 1.62501847, -0.08546013, -0.18432667],
       [ 0.22045906, -0.12274378, -1.4605252 ],
       [ 0.90225651,  0.08120726,  0.37361106],
       [ 0.83766328,  0.24535649, -0.44322096],
       [-0.56756442,  0.8292632 , -0.30032537]])

In [22]:
arr.mean(axis=1)

array([ 0.45174389, -0.45426997,  0.45235827,  0.21326627, -0.01287553])

In [23]:
arr

array([[ 1.62501847, -0.08546013, -0.18432667],
       [ 0.22045906, -0.12274378, -1.4605252 ],
       [ 0.90225651,  0.08120726,  0.37361106],
       [ 0.83766328,  0.24535649, -0.44322096],
       [-0.56756442,  0.8292632 , -0.30032537]])

In [25]:
arr2=arr.mean(axis=1)
arr2

array([ 0.45174389, -0.45426997,  0.45235827,  0.21326627, -0.01287553])

In [28]:
np.random.normal(size=(4,4))

array([[-1.54263869, -0.16522276,  1.69415283,  1.50996709],
       [-1.11339292,  0.6174794 , -0.66353242,  0.1856653 ],
       [ 0.41832076,  0.50556986,  0.90065598,  0.73266187],
       [-1.17191066, -0.67588965, -0.97291652,  0.52003328]])

In [31]:
np.random.rand(2,3)

array([[0.02960884, 0.74002643, 0.76787667],
       [0.80245443, 0.1819588 , 0.36769807]])

In [33]:
np.random.randint(low=2,high=10,size=(2,3),dtype='int64')

array([[2, 5, 9],
       [6, 2, 7]], dtype=int64)

In [34]:
np.random.binomial(3,0.1,size=(2,3))

array([[1, 0, 1],
       [1, 1, 0]])

In [35]:
np.random.normal(size=(2,2))

array([[ 0.00294432,  1.22015084],
       [-0.31913346, -1.05980967]])

In [39]:
np.random.beta(1,2,size=100)

array([0.44604919, 0.01371454, 0.71698987, 0.36180772, 0.15096887,
       0.28833967, 0.70917404, 0.39793463, 0.17712597, 0.50629763,
       0.69410652, 0.09024021, 0.24435223, 0.01448121, 0.44387067,
       0.07917509, 0.18053498, 0.17583454, 0.21095502, 0.21088388,
       0.25059365, 0.59322124, 0.67781359, 0.80149349, 0.54086765,
       0.70081365, 0.19720442, 0.35762082, 0.37030697, 0.12739402,
       0.66342381, 0.14822883, 0.02828356, 0.0047534 , 0.40665701,
       0.79764894, 0.13640797, 0.15339084, 0.39434267, 0.27380241,
       0.02559958, 0.3175853 , 0.32523417, 0.80355653, 0.44895183,
       0.65045016, 0.05286792, 0.00465281, 0.11401837, 0.58561718,
       0.27916956, 0.26498057, 0.25950472, 0.25286966, 0.26283325,
       0.08426135, 0.48171527, 0.55050451, 0.55035128, 0.10929398,
       0.43949938, 0.85445333, 0.01055144, 0.47356409, 0.21238285,
       0.24776301, 0.45282314, 0.12936354, 0.08065309, 0.129812  ,
       0.63019344, 0.40238311, 0.62676231, 0.39116814, 0.38928

In [38]:
np.random.chisquare()

TypeError: chisquare() takes at least 1 positional argument (0 given)

In [40]:
np.random.randint(low=0,high=2,size=10)

array([0, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [46]:
arr=np.random.randint(1,10,size=(3,3))
arr.cumsum()


array([ 9, 15, 24, 32, 36, 44, 49, 53, 57], dtype=int32)

In [3]:
import numpy as np


In [10]:
dt=np.dtype([
    ('name','S'),('age','i4'),
    ('Height','f'),('Children','i4',2)
])
s=np.array([['Smith',45,1.83,(0,1)]],dtype=dt)

ValueError: invalid literal for int() with base 10: 'Smith'

In [1]:
import numpy as np

In [2]:
arr=np.array([[3,1,1],[2,0,2],[1,3,0]])

In [3]:
inv=np.linalg.inv(arr)

In [4]:
inv

array([[ 0.6, -0.3, -0.2],
       [-0.2,  0.1,  0.4],
       [-0.6,  0.8,  0.2]])

In [5]:
a=np.array([3,4,5])

In [6]:
a.T|

array([3, 4, 5])

In [7]:
A

array([3, 4, 5])

In [8]:
inv@a

array([-0.4,  1.8,  2.4])

In [10]:
a.T@a

50