In [1]:
import torch

In [2]:
z=torch.linspace(start=-100,end=100,steps=10)

In [3]:
z

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5555,   77.7778,  100.0000])

In [4]:
new_z=torch.sigmoid(z)

In [5]:
new_z

tensor([0.0000e+00, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])

In [2]:
from torch.nn import functional as F

In [3]:
x=torch.ones(1)
w=torch.full([1],2)
mse=F.mse_loss(torch.ones(1),x*w)

In [5]:
torch.autograd.grad(mse,w)  #第一个是函数，第二个是需要求导的变量
#会报错，因为没有设置追踪w

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [6]:
w.requires_grad_()

tensor([2.], requires_grad=True)

In [7]:
torch.autograd.grad(mse,w)  #仍然报错，因为他没有更新函数，mse要更新才可以，pytorch是一步一步更新的

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [8]:
mse=F.mse_loss(torch.ones(1),x*w)

In [9]:
torch.autograd.grad(mse,w)  #这样就可以了

(tensor([2.]),)

In [11]:
mse=F.mse_loss(torch.ones(1),w*x)
mse.backward()

In [12]:
w.grad

tensor([2.])

In [17]:
a=torch.rand(3,requires_grad=True)

In [6]:
a.requires_grad_()

tensor([0.1687, 0.3668, 0.3696], requires_grad=True)

In [7]:
from torch.nn import functional as F

In [8]:
p=F.softmax(a)

D:\software\Anaconda\envs\data\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [10]:
p.backward()    #这里p是一个向量，是无法用来求导的

RuntimeError: grad can be implicitly created only for scalar outputs

In [11]:
p=F.softmax(a,dim=0)

In [13]:
torch.autograd.grad(p[1],a)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [14]:
p=F.softmax(a)

D:\software\Anaconda\envs\data\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [15]:
torch.autograd.grad(p[2],a,retain_graph=True)

(tensor([-0.1032, -0.1258,  0.2290]),)

In [16]:
torch.autograd.grad(p[1],a,retain_graph=True)

(tensor([-0.1029,  0.2287, -0.1258]),)

In [2]:
import torch
x=torch.randn(1,10)
w=torch.randn(1,10,requires_grad=True)

In [5]:
o=torch.sigmoid(x@w.t())

In [6]:
o.shape

torch.Size([1, 1])

In [8]:
from torch.nn import functional as F

In [9]:
loss=F.mse_loss(torch.ones(1,1),o)

In [10]:
loss.backward()

In [11]:
w.grad

tensor([[-0.0101,  0.0460,  0.0315, -0.0070, -0.0705, -0.0190, -0.0235, -0.1026,
         -0.0350, -0.0197]])

In [12]:
x=torch.randn(1,10)
w=torch.randn(2,10,requires_grad=True)

In [13]:
o=torch.sigmoid(x@w.t())

In [14]:
loss=F.mse_loss(torch.ones(1,2),o)

In [15]:
loss.backward()

In [16]:
w.grad

tensor([[-2.1282e-02, -6.4585e-03,  9.9112e-03, -2.6978e-02, -5.9556e-03,
         -9.9134e-03,  3.6317e-02,  5.5082e-02,  3.0404e-03,  4.5578e-02],
        [-4.9471e-05, -1.5013e-05,  2.3039e-05, -6.2712e-05, -1.3844e-05,
         -2.3044e-05,  8.4420e-05,  1.2804e-04,  7.0676e-06,  1.0595e-04]])