In [3]:
import torch

In [5]:
#检验一下数据类型，直接用对象调用type()方法
a=torch.randn(2,3)  
a.type()

'torch.FloatTensor'

In [6]:
type(a) #type()只会返回一个比较基础的类型，不是很好

torch.Tensor

In [15]:
b=torch.tensor(3.)

In [14]:
a.shape

torch.Size([2, 3])

In [16]:
b.shap

torch.Size([])

In [17]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [19]:
torch.FloatTensor(3)

tensor([0., 0., 0.])

In [22]:
import numpy as np

In [34]:
data=np.ones((2,3))

In [35]:
data=torch.from_numpy(data)

In [36]:
data.shape[0]

2

In [37]:
data.shape[1]

3

In [38]:
torch.rand(2,3)

tensor([[0.3588, 0.8932, 0.5195],
        [0.1432, 0.9837, 0.6882]])

In [40]:
torch.randint(2,3,(2,2))

tensor([[2, 2],
        [2, 2]])

In [41]:
a=torch.randn(4,3,28,28)

In [44]:
a[0].shape

torch.Size([3, 28, 28])

In [46]:
a[0,0].shape

torch.Size([28, 28])

In [48]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [51]:
a.shape

torch.Size([4, 3, 28, 28])

In [52]:
a.reshape([4,3,28*28])

tensor([[[ 0.5153, -2.1083,  0.0141,  ...,  1.6091, -0.5246, -0.5794],
         [ 0.4813,  0.5667,  0.4234,  ...,  0.2181, -0.0942, -1.0432],
         [ 0.4380,  0.6609,  0.5129,  ..., -0.8578, -0.0308, -1.1497]],

        [[ 0.6284, -1.3992,  1.1652,  ...,  0.4254,  1.2571,  0.0623],
         [ 0.1156, -0.9246, -2.1398,  ...,  0.7506, -0.0059,  0.6765],
         [-0.5024, -0.9896,  1.4876,  ...,  0.7429,  0.3138,  0.1842]],

        [[ 1.4255,  1.2618,  0.3625,  ..., -0.5087,  0.9021,  0.8896],
         [-1.1538,  0.6839, -1.0087,  ...,  0.8734,  0.3524, -0.4451],
         [ 0.2815,  1.2648,  1.3413,  ..., -2.3505,  0.1097, -0.3855]],

        [[ 0.7972, -1.5757,  0.4078,  ...,  0.5928, -1.2397, -0.4492],
         [-0.9256, -0.3643, -1.1263,  ...,  1.2608,  0.6944,  0.6976],
         [-1.0190, -1.1587,  1.4476,  ..., -1.4260,  0.3977,  1.7758]]])

In [54]:
a.unsqueeze(0).shape

torch.Size([1, 4, 3, 28, 28])

In [56]:
a.unsqueeze(-2).shape

torch.Size([4, 3, 28, 1, 28])

In [57]:
b=torch.randn(1,1,23,1)

In [58]:
b.shape

torch.Size([1, 1, 23, 1])

In [60]:
b.squeeze(0).shape

torch.Size([1, 23, 1])

In [2]:
a=torch.randn(1,4)

In [6]:
a

tensor([[-1.1639,  1.4806,  0.4077,  1.0021]])

In [14]:
a=a.expand(3,4)

In [9]:
b=torch.randn(4)

In [16]:
b.expand_as(a)

tensor([[-0.9573,  1.6805,  0.6539, -1.6508],
        [-0.9573,  1.6805,  0.6539, -1.6508],
        [-0.9573,  1.6805,  0.6539, -1.6508]])

In [11]:
b.expand(3,4)

tensor([[-0.9573,  1.6805,  0.6539, -1.6508],
        [-0.9573,  1.6805,  0.6539, -1.6508],
        [-0.9573,  1.6805,  0.6539, -1.6508]])

In [13]:
b.expand(2,2,4)

tensor([[[-0.9573,  1.6805,  0.6539, -1.6508],
         [-0.9573,  1.6805,  0.6539, -1.6508]],

        [[-0.9573,  1.6805,  0.6539, -1.6508],
         [-0.9573,  1.6805,  0.6539, -1.6508]]])

In [1]:
import torch

In [2]:
a=torch.randn(3,32,8)
b=torch.randn(4,32,8)

In [11]:
c=torch.cat(tensors=[a,b],dim=0)

In [12]:
c.shape

torch.Size([7, 32, 8])

In [13]:
d=torch.stack(tensors=[a,b],dim=0)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 4 in dimension 1 at C:\w\1\s\tmp_conda_3.7_183424\conda\conda-bld\pytorch_1570818936694\work\aten\src\TH/generic/THTensor.cpp:689

In [14]:
a=torch.randn(4,32,8)

In [15]:
d=torch.stack(tensors=[a,b],dim=0)

In [16]:
d.shape

torch.Size([2, 4, 32, 8])

In [19]:
c.shape

torch.Size([7, 32, 8])

In [20]:
aa,bb=c.split(split_size=[3,4],dim=0)

In [23]:
print(aa.shape)
print(bb.shape)

torch.Size([3, 32, 8])
torch.Size([4, 32, 8])


In [24]:
dd,ee,ff=c.split(split_size=[1,3,3],dim=0)

In [26]:
c.shape

torch.Size([7, 32, 8])

In [29]:
ff,gg=c.chunk(chunks=2,dim=1)

In [31]:
print(ff.shape,gg.shape)

torch.Size([7, 16, 8]) torch.Size([7, 16, 8])


In [32]:
a=torch.exp(torch.ones(2,2))

In [37]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

In [38]:
torch.log2(a)

tensor([[1.4427, 1.4427],
        [1.4427, 1.4427]])

In [39]:
grad=torch.rand(2,3)*15

In [40]:
grad

tensor([[ 4.0210,  7.4417, 10.4536],
        [14.4394,  4.3195,  3.2489]])

In [4]:
test=torch.tensor([[2,4,5,6],[5,6,7,9]])

In [5]:
print(test.argmax(),test.argmin())  #返回打平后的索引，就是第0位置，和第7位置

tensor(7) tensor(0)


In [6]:
test.argmax(dim=1)

tensor([3, 3])

In [7]:
test.max(dim=1) #这个返回一个tuple，第一个是values的列表，另一个是索引，每行的

torch.return_types.max(
values=tensor([6, 9]),
indices=tensor([3, 3]))

In [8]:
test.max(dim=1,keepdim=True)

torch.return_types.max(
values=tensor([[6],
        [9]]),
indices=tensor([[3],
        [3]]))

In [9]:
cond=torch.rand(2,2)
cond

tensor([[0.8085, 0.7105],
        [0.2334, 0.4978]])

In [10]:
a=torch.zeros(2,2)
b=torch.ones(2,2)

In [0]:
torch.where(cond>0.5,a,b)

In [1]:
import torch

In [3]:
points=torch.tensor([[1,2,3],[4,5,6]]).float()  #直接可以用方法进行定义对象

In [7]:
points.to(dtype=torch.double)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [8]:
points.numpy()  #使用numpy方法可以将tensor转换成Numpy

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
torch.save(points,'./test.t')

In [10]:
test=torch.load(f='./test.t')

In [11]:
test

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
import numpy as np

In [13]:
new_data=np.array([[1,2,34],[2,323,23]])

In [20]:
import h5py

In [21]:
f=h5py.File(name='./h5_test.hdf5',mode='w')

In [22]:
f.create_dataset(name='new',data=new_data)

<HDF5 dataset "new": shape (2, 3), type "<i4">

In [23]:
f.close()

In [24]:
f=h5py.File(name='./h5_test.hdf5',mode='r')
a=f['new']

In [26]:
a[:,:]

array([[  1,   2,  34],
       [  2, 323,  23]])

In [27]:
points.zero_()  #可以将矩阵全部变为0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [29]:
points

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [2]:
import torch
import numpy as np
import pandas as pd

In [9]:
temp_df=pd.read_csv('basic\winequality-white.csv',sep=';')

In [10]:
temp_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [14]:
df=torch.from_numpy(temp_df.values)

In [16]:
df

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
        [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]],
       dtype=torch.float64)

In [17]:
data=df[:,:-1]
target=df[:,-1]

In [19]:
target.long()  

tensor([6, 6, 6,  ..., 6, 7, 6])

In [49]:
target_onehot=torch.zeros(target.shape[0],10)

In [48]:
target_onehot.scatter_(1, target.unsqueeze(1).long(), 1.0)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [50]:
target_onehot.scatter_(dim=1,index=target.unsqueeze(1).long(),value=1.0)    #You should use long type

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [51]:
data_mean=data.mean(dim=0)

In [52]:
torch.le(target,3)  #return bool matrix

tensor([False, False, False,  ..., False, False, False])

In [53]:
data=data[target<=3]f

In [54]:
data.shape

torch.Size([20, 11])

In [60]:
with open('basic/1342-0.txt',mode='r',encoding='utf-8') as f:
    text=f.read()

In [63]:
lines=text.split('\n')
line=lines[200].strip()

In [64]:
line

'Michaelmas, and some of his servants are to be in the house by'

In [65]:
letter_tensor=torch.zeros(len(line),128)

In [ ]:
letter_tensor.shape